workspace(name = "cctest_examples")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# curl -L https://github.com/ccup/cctest/archive/release-1.0.tar.gz | sha256sum
http_archive(
    name = "github_ccup_cctest",
    sha256 = "6391110348fa4543df6251e4b0ac237ea5f5009dc425b438c25d1325c3aa3ead",
    strip_prefix = "cctest-release-1.0",
    urls = [
        "https://github.com/ccup/cctest/archive/release-1.0.tar.gz",
    ],
)
